### ISSUE TITLE
Alterar os títulos dos capítulos 

### ISSUE THREAD

**Issue by ViniciusmDias** [ChristySchott/manual-node#4]
Notei que no livro original os capítulos tem meio que um "titulo"[1] em letra preta e estamos usando o primeiro tópico[2] do capítulo como h1 centralizado[3] nos arquivos de tradução. Segue abaixo fotos exemplificando os pontos 1, 2 e 3.

[1]
![image](https://user-images.githubusercontent.com/23238171/87960881-53001280-ca8b-11ea-9d9c-c739d12cb484.png)

[2]
![image](https://user-images.githubusercontent.com/23238171/87961600-53e57400-ca8c-11ea-90d7-145b8a8cabcd.png)

[3]
![image](https://user-images.githubusercontent.com/23238171/87961571-43cd9480-ca8c-11ea-816b-9816e4aadc64.png)

### Sugestão inicial: 

- Deixarmos aquele primeiro h1 centralizado de cada Capitulo_*.md como o titulo preto original, visto na figura 1.

**Comment by ChristySchott** [comment]
Perfeito! Vai ser editado agora mesmo.

**Comment by ViniciusmDias** [comment]
Boaaa, mandou muito!
